"""
Django settings for mi_sitio_web project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os # Asegúrate de que esta línea esté presente

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tu_clave_secreta_aqui' # Deja la que ya tienes o genera una nueva y segura

# SECURITY WARNING: don't run with debug turned on in production!
# ¡IMPORTANTE! Esto debería ser False en producción.
# Puedes usar una variable de entorno para cambiarlo en PythonAnywhere si lo deseas.
# Por ahora, para pruebas iniciales, podríamos dejarlo True para ver errores,
# pero LUEGO debe ser False para despliegue real.
DEBUG = True # O False, si quieres empezar directamente con producción.

# Define los hosts permitidos para tu aplicación. ¡MUY IMPORTANTE para PythonAnywhere!
ALLOWED_HOSTS = [
    '127.0.0.1',                # Para desarrollo local
    'localhost',                # Para desarrollo local
    'agusp80.pythonanywhere.com', # ¡Tu dominio en PythonAnywhere!
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog', # ¡Asegúrate de que tu app 'blog' esté aquí!
    # Agrega otras apps de terceros si las tienes (como rest_framework, etc.)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mi_sitio_web.urls' # Asegúrate de que apunte a tu urls.py principal

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Puedes agregar BASE_DIR / 'templates' aquí si tienes templates globales
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_sitio_web.wsgi.application' # Asegúrate de que apunte a tu wsgi.py principal


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', # La base de datos estará en la raíz de tu proyecto
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-ar' # Código de idioma para Argentina (Buenos Aires)

TIME_ZONE = 'America/Argentina/Buenos_Aires' # Zona horaria para Buenos Aires

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Aquí se copiarán los archivos estáticos en producción

# Media files (archivos subidos por los usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Aquí se guardarán los archivos subidos en producción


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF_TRUSTED_ORIGINS (Opcional, pero recomendado si tienes problemas con formularios en producción)
CSRF_TRUSTED_ORIGINS = ['https://agusp80.pythonanywhere.com']